spring.application.name=payment-engine

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


outbox.processing.delay=5000
outbox.processing.batch-size=100
outbox.processing.max-retries=5


logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF


springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always